language: node_js

node_js:
  - 9.5.0

script:
    - npm run unit:test

deploy: 
  provider: heroku
  # from heroku
  app: tap-deploy-test
  api_key:
    secure: $HEROKU_API_KEY
  # when travis should be triggered
  on:
    branch: master